spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: <id>
            client-secret: <secret>
          google:
            client-id: <id>
            client-secret: <secret> 

#logging:
#  level:
#    org.springframework.security: DEBUG
